let arr = [1,2,3,4,5];
console.log(arr);
console.log(arr[3]);
console.log(arr.length);
arr.push(6);
console.log(arr);
arr.pop();
console.log(arr);
arr.unshift(0);
console.log(arr);
arr.shift();
console.log(arr);
arr.splice(2,1);
console.log(arr);
arr.splice(2,0,3);
console.log(arr);
arr.slice(2,1);
console.log(arr);
